import "dotenv/config";
import { Pool } from "pg";
import { PrismaClient } from "../generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.analyticsEvent.deleteMany();
  await prisma.auditLog.deleteMany();
  await prisma.location.deleteMany();
  await prisma.category.deleteMany();
  await prisma.admin.deleteMany();

  // ── Categories ──
  const categories = await Promise.all([
    prisma.category.create({ data: { name: "Tarihi Yapılar", nameEn: "Historical Sites", icon: "landmark", color: "#b45309", slug: "historical", sortOrder: 1 } }),
    prisma.category.create({ data: { name: "Antik Kentler", nameEn: "Ancient Cities", icon: "columns-3", color: "#92400e", slug: "ancient", sortOrder: 2 } }),
    prisma.category.create({ data: { name: "Müzeler", nameEn: "Museums", icon: "building-2", color: "#7c3aed", slug: "museum", sortOrder: 3 } }),
    prisma.category.create({ data: { name: "Doğal Alanlar", nameEn: "Natural Areas", icon: "trees", color: "#16a34a", slug: "nature", sortOrder: 4 } }),
    prisma.category.create({ data: { name: "Plajlar & Adalar", nameEn: "Beaches & Islands", icon: "waves", color: "#0891b2", slug: "beach", sortOrder: 5 } }),
    prisma.category.create({ data: { name: "Kültürel Mekanlar", nameEn: "Cultural Venues", icon: "palette", color: "#db2777", slug: "cultural", sortOrder: 6 } }),
    prisma.category.create({ data: { name: "Gastronomi", nameEn: "Gastronomy", icon: "utensils", color: "#ea580c", slug: "gastronomy", sortOrder: 7 } }),
    prisma.category.create({ data: { name: "Termal & Jeopark", nameEn: "Thermal & Geopark", icon: "flame", color: "#dc2626", slug: "thermal", sortOrder: 8 } }),
    prisma.category.create({ data: { name: "Dini Yapılar", nameEn: "Religious Sites", icon: "church", color: "#6d28d9", slug: "religious", sortOrder: 9 } }),
  ]);
  const [historical, ancient, museum, nature, beach, cultural, gastronomy, thermal, religious] = categories;

  // ── Locations ──
  const locations = [
    // ═══ HISTORICAL SITES (7) ═══
    {
      name: `Zağnos Paşa Camii ve Külliyesi`, nameEn: `Zagnos Pasha Mosque & Complex`,
      description: `Zağnos Paşa Camii, 1461 yılında Fatih Sultan Mehmed'in sadrazamı ve İstanbul'un fethinde kilit rol oynayan Arnavut kökenli komutan Zağnos Paşa tarafından yaptırılmıştır. Balıkesir'in en büyük camisi olan yapı, kesme taş işçiliğiyle inşa edilmiş olup bir ana kubbe ve dört yan kubbeden oluşur. Külliye bünyesinde türbe, hamam ve şadırvanlar bulunmaktadır. 1897 depreminde hasar gören cami, 1908'de yeniden inşa edilmiştir. Mustafa Kemal Atatürk, 7 Şubat 1923'te bu camide ünlü Balıkesir Hutbesi'ni okumuştur.`,
      descriptionEn: `Zagan Pasha Mosque was built in 1461 by Zagan Pasha, an Ottoman Grand Vizier of Albanian origin who played a crucial role in the Conquest of Constantinople under Sultan Mehmed II. The largest mosque in Balıkesir, constructed in ashlar masonry with one main dome and four side domes. The complex includes a tomb, hammam, and ornamental fountains. Damaged in the 1897 earthquake, rebuilt in 1908. Atatürk delivered his famous Balıkesir Khutbah here on February 7, 1923.`,
      shortDesc: `1461 Erken Osmanlı başyapıtı, Balıkesir Hutbesi mekanı`, shortDescEn: `1461 Early Ottoman masterpiece, site of historic Balıkesir Sermon`,
      latitude: 39.64861, longitude: 27.87972, categoryId: historical.id,
      images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Za%C4%9Fnos_Pa%C5%9Fa_Camii.jpg/800px-Za%C4%9Fnos_Pa%C5%9Fa_Camii.jpg"],
      visitHours: `Her gün 05:00-22:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Hisariçi Mah., Zağnos Paşa Cad., Karesi, Balıkesir`, addressEn: `Hisariçi District, Zağnos Paşa St., Karesi, Balıkesir`,
      publicTransport: `Balıkesir şehir içi otobüsleri ile Zağnos Mahallesi durağında inin. Merkez otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Zağnos Mahallesi stop. 10 min walk from central bus station.`,
      isFeatured: true,
    },
    {
      name: `Balıkesir Saat Kulesi`, nameEn: `Balıkesir Clock Tower`,
      description: `İlk yapımı 1827'ye dayanan, 1897 depreminde yıkıldıktan sonra 1901'de yeniden inşa edilen 20 metre yüksekliğindeki saat kulesi. Klasik Osmanlı mimari üslubunda tasarlanmış, şehrin en tanınmış simgelerinden biridir.`,
      descriptionEn: `Originally built in 1827, rebuilt in 1901 after the 1897 earthquake. Rising 20 meters high in classical Ottoman architectural style, it is one of the city's most recognizable landmarks and a focal point of the city square.`,
      shortDesc: `1827'den kalma şehir simgesi`, shortDescEn: `City symbol dating from 1827`,
      latitude: 39.64528, longitude: 27.87917, categoryId: historical.id,
      images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bal%C4%B1kesir_Clock_Tower_front_view%2C_Bal%C4%B1kesir%2C_2023.jpg/800px-Bal%C4%B1kesir_Clock_Tower_front_view%2C_Bal%C4%B1kesir%2C_2023.jpg"],
      visitHours: `Dış mekan, her zaman görülebilir`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Belediye Parkı içi, Karesi, Balıkesir`, addressEn: `Inside Municipality Park, Karesi, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Çarşı/Merkez durağında inin. Otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Çarşı/Merkez stop. 10 min walk from bus station.`,
      isFeatured: true,
    },
    {
      name: `Havran Terzizade Konağı (Atatürk ve Seyit Onbaşı Müzesi)`, nameEn: `Havran Terzizade Mansion (Atatürk & Seyit Onbaşı Museum)`,
      description: `19. yüzyıl Osmanlı sivil mimarisinin Havran'daki en görkemli örneklerinden biri. Atatürk ile Çanakkale kahramanı Seyit Onbaşı'nın tarihi buluşmasına ev sahipliği yapmıştır. 2023'te müze olarak açılmıştır.`,
      descriptionEn: `One of the most magnificent examples of 19th-century Ottoman civil architecture in Havran. Hosted the historic meeting between Atatürk and war hero Seyit Onbaşı. Opened as museum in 2023.`,
      shortDesc: `Atatürk-Seyit Onbaşı buluşma mekanı, 2023 müze`, shortDescEn: `Atatürk-Seyit Onbaşı meeting place, 2023 museum`,
      latitude: 39.5572, longitude: 27.0989, categoryId: historical.id,
      images: ["https://images.unsplash.com/photo-1590076082562-e7e3e1e0c1f4?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Havran, Balıkesir`, addressEn: `Havran, Balıkesir`,
      publicTransport: `Balıkesir otogarından Havran dolmuşları 30 dk arayla kalkar. Havran merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Minibuses to Havran every 30 min from Balıkesir station. 5 min walk from Havran center.`,
      isFeatured: true,
    },
    {
      name: `Sındırgı Kışla Müze Han`, nameEn: `Sındırgı Kışla Museum Inn`,
      description: `Kesme taş mimarisiyle hayranlık uyandıran tarihi yapı. 8 odalı butik otele ve kültür kompleksine dönüştürülmüştür. Sındırgı'nın UNESCO Küresel Jeopark adaylık sürecinin kültürel vitrinlerinden biridir.`,
      descriptionEn: `Historic building admired for its cut-stone architecture. Transformed into an 8-room boutique hotel and cultural complex, a showcase of Sındırgı's UNESCO Global Geopark candidacy.`,
      shortDesc: `Tarihi askeri yapı, butik otel ve kültür kompleksi`, shortDescEn: `Historic military building, boutique hotel & cultural complex`,
      latitude: 39.3208, longitude: 28.1756, categoryId: historical.id,
      images: ["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1024&q=80"],
      visitHours: `Her gün 09:00-22:00`,
      fee: `Müze ücretsiz, konaklama ücretli`, feeEn: `Museum free, accommodation paid`,
      address: `Sındırgı Merkez, Balıkesir`, addressEn: `Sındırgı Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Sındırgı otobüsleri günde 8-10 sefer (1.5 saat). Merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Buses to Sındırgı 8-10 times daily (1.5 hours). 5 min walk from center.`,
    },
    {
      name: `Yıldırım Camii ve Külliyesi`, nameEn: `Yıldırım Bayezid Mosque & Complex`,
      description: `1388'de Yıldırım Beyazıt tarafından yaptırılan Balıkesir'in en eski Osmanlı eseri. Dikdörtgen planlı, üç nefli, devşirme sütunlu cami. Külliye içinde medrese ve imaret kalıntıları bulunuyor.`,
      descriptionEn: `Built in 1388 by Sultan Bayezid I, the oldest Ottoman monument in Balıkesir. Rectangular plan with three naves and spolia columns. Complex includes madrasa and soup kitchen remains.`,
      shortDesc: `1388, Balıkesir'in en eski Osmanlı eseri`, shortDescEn: `1388, oldest Ottoman monument in Balıkesir`,
      latitude: 39.6475, longitude: 27.881, categoryId: historical.id,
      images: ["https://images.unsplash.com/photo-1564769625905-50e93615e769?w=1024&q=80"],
      visitHours: `Her gün 05:00-22:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Yıldırım Mah., Gazi Bulvarı, Karesi, Balıkesir`, addressEn: `Yıldırım District, Gazi Boulevard, Karesi, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Yıldırım durağında inin. Otogardan yürüyerek 12 dk.`,
      publicTransportEn: `Take city buses to Yıldırım stop. 12 min walk from bus station.`,
      isFeatured: true,
    },
    {
      name: `Karesi Bey Camii ve Külliyesi`, nameEn: `Karesi Bey Mosque & Complex`,
      description: `Karesi Beyliği dönemine ait, 1464 tarihli kitabesiyle bilinen cami ve külliye. 1897 depreminde yıkılan yapı, 1908'de yeniden inşa edilmiştir. Hamam özgün halini korumaktadır.`,
      descriptionEn: `Mosque and complex from the Karesi Beylik period, known from its 1464 inscription. Rebuilt in 1908 after the 1897 earthquake. The hammam preserves its original form.`,
      shortDesc: `Karesi Beyliği dönemi cami ve külliyesi`, shortDescEn: `Karesi Beylik period mosque and complex`,
      latitude: 39.649, longitude: 27.8785, categoryId: historical.id,
      images: ["https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=1024&q=80"],
      visitHours: `Her gün 05:00-22:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Mustafa Fakıh Mah., Çarşı içi, Karesi, Balıkesir`, addressEn: `Mustafa Fakıh District, Market area, Karesi, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Çarşı durağında inin. Otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Çarşı stop. 10 min walk from bus station.`,
    },
    {
      name: `Değirmenboğazı Köprüsü`, nameEn: `Değirmenboğazı Bridge`,
      description: `1390'da Yıldırım Beyazıt tarafından yaptırılan üç kemerli taş köprü. 30 m uzunluğunda ve 4 m genişliğinde. Kemerler yarımdaire biçimli, ortadaki kemer daha büyük. Yıldırım Beyazıt Köprüsü olarak da bilinir.`,
      descriptionEn: `Three-arched stone bridge built in 1390 by Sultan Bayezid I. 30 m long and 4 m wide with semicircular arches, the central arch being larger. Also known as Yıldırım Beyazıt Bridge.`,
      shortDesc: `1390 Osmanlı taş köprüsü`, shortDescEn: `1390 Ottoman stone bridge`,
      latitude: 39.635, longitude: 27.865, categoryId: historical.id,
      images: ["https://images.unsplash.com/photo-1568322503122-d237ab09f422?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Değirmenboğazı Mevkii, Ayvatlar, Balıkesir Merkez`, addressEn: `Değirmenboğazı Area, Ayvatlar, Balıkesir Center`,
      publicTransport: `Balıkesir merkezden Değirmenboğazı Mesire Alanı'na dolmuş veya taksi (15 dk).`,
      publicTransportEn: `Minibus or taxi from Balıkesir center to Değirmenboğazı Recreation Area (15 min).`,
    },
    // ═══ ANCIENT CITIES (5) ═══
    {
      name: `Antandros Antik Kenti`, nameEn: `Antandros Ancient City`,
      description: `Kazdağları'nın güney eteklerinde, 215 metre yüksekliğindeki Kaletaşı tepesinde kurulmuş antik Troas kenti. MÖ 7. yüzyılda Lelegler tarafından kurulduğu rivayet edilir. İkinci Efes olarak nitelendirilen yamaç evleri, Anadolu'da Efes'ten sonra en iyi korunmuş duvar freskleri ve zemin mozaiklerine sahiptir.`,
      descriptionEn: `Ancient Troad city on the 215m Kaletaşı hilltop on the southern slopes of Mount Ida. Its hillside houses, dubbed Second Ephesus, have the best-preserved wall frescoes and floor mosaics in Anatolia after Ephesus.`,
      shortDesc: `İkinci Efes: Roma freskleri ve mozaikleri`, shortDescEn: `Second Ephesus: Roman frescoes and mosaics`,
      latitude: 39.575, longitude: 26.7908, categoryId: ancient.id,
      images: ["https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=1024&q=80"],
      visitHours: `Salı-Pazar 08:30-17:30`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Altınoluk, Edremit, Balıkesir`, addressEn: `Altınoluk, Edremit, Balıkesir`,
      publicTransport: `Balıkesir otogarından Edremit/Altınoluk otobüsü (2 saat). Altınoluk merkezden yürüyerek 15 dk.`,
      publicTransportEn: `Bus from Balıkesir to Edremit/Altınoluk (2 hours). 15 min walk from Altınoluk center.`,
      isFeatured: true,
    },
    {
      name: `Adramytteion Antik Kenti`, nameEn: `Adramytteion Ancient City`,
      description: `Burhaniye'nin 4 km batısında Ören sahil mahallesinde kurulmuş antik Aiolis kenti. MÖ 4. yüzyıldan itibaren önemli ticaret ve denizcilik merkezi. 2020 ve 2025'te deniz seviyesinin düşmesiyle antik liman kalıntıları gün yüzüne çıkmıştır.`,
      descriptionEn: `Ancient Aeolian city at the coastal neighborhood of Ören in Burhaniye. Significant trade center from 4th century BC. In 2020 and 2025, receding sea levels revealed ancient port remains.`,
      shortDesc: `Antik liman kenti, Ege ticaret düğüm noktası`, shortDescEn: `Ancient port city, Aegean trade hub`,
      latitude: 39.59306, longitude: 27.02028, categoryId: ancient.id,
      images: ["https://images.unsplash.com/photo-1568322503122-d237ab09f422?w=1024&q=80"],
      visitHours: `Salı-Pazar 08:30-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Ören, Burhaniye, Balıkesir`, addressEn: `Ören, Burhaniye, Balıkesir`,
      publicTransport: `Balıkesir otogarından Burhaniye otobüsü (1.5 saat), ardından Ören dolmuşu (15 dk).`,
      publicTransportEn: `Bus from Balıkesir to Burhaniye (1.5 hours), then minibus to Ören (15 min).`,
    },
    {
      name: `Daskyleion Antik Kenti`, nameEn: `Daskyleion Ancient City`,
      description: `Manyas Gölü güneybatı kıyısında, Bandırma Ergili köyü yakınlarında yer alan antik kent. MÖ 6. yüzyılda Pers İmparatorluğu'nun Hellespontos Phrygia satraplığının başkenti. Kybele tapınağı temelleri ve Pers dönemi kabartmaları bulunmuştur.`,
      descriptionEn: `Ancient city near Ergili village in Bandırma, on the southwestern shore of Lake Manyas. Capital of the Persian satrapy of Hellespontine Phrygia in the 6th century BC. Cybele temple foundations and Persian reliefs found.`,
      shortDesc: `MÖ 7. yüzyıl Pers satraplık merkezi`, shortDescEn: `7th century BC Persian satrapy center`,
      latitude: 40.1321, longitude: 28.051, categoryId: ancient.id,
      images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Ergili, Bandırma, Balıkesir`, addressEn: `Ergili, Bandırma, Balıkesir`,
      publicTransport: `Balıkesir otogarından Bandırma otobüsü (1.5 saat). Bandırma'dan Ergili köyüne dolmuş veya taksi (20 dk).`,
      publicTransportEn: `Bus from Balıkesir to Bandırma (1.5 hours). Minibus or taxi to Ergili village (20 min).`,
      isFeatured: true,
    },
    {
      name: `Kyzikos Antik Kenti`, nameEn: `Kyzikos Ancient City`,
      description: `Kapıdağ Yarımadası'nda kurulmuş Mysia bölgesinin en önemli antik Yunan kentlerinden biri. İmparator Hadrianus Tapınağı burada inşa edilmiş olup sütunları 21.35 metre yüksekliğiyle Baalbek'tekileri aşmaktadır. Kyzikos altın sikkeleri antik dünyada temel para birimi olarak kullanılmıştır.`,
      descriptionEn: `One of the most important ancient Greek cities of Mysia on the Kapıdağ Peninsula. The Temple of Emperor Hadrian had columns reaching 21.35 meters, surpassing Baalbek. Gold staters of Cyzicus served as staple currency throughout the ancient world.`,
      shortDesc: `Hadrian Tapınağı ve antik darphane kenti`, shortDescEn: `Temple of Hadrian and ancient mint city`,
      latitude: 40.39, longitude: 27.88361, categoryId: ancient.id,
      images: ["https://images.unsplash.com/photo-1564769625905-50e93615e769?w=1024&q=80"],
      visitHours: `Her gün gündüz saatleri`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Düzler Köyü, Erdek, Balıkesir`, addressEn: `Düzler Village, Erdek, Balıkesir`,
      publicTransport: `Bandırma'dan Erdek dolmuşları sık sefer yapar (45 dk). Erdek'ten Düzler köyüne taksi (10 dk).`,
      publicTransportEn: `Frequent minibuses from Bandırma to Erdek (45 min). Taxi from Erdek to Düzler village (10 min).`,
      isFeatured: true,
    },
    {
      name: `Saraylar Açık Hava Müzesi`, nameEn: `Saraylar Open-Air Museum`,
      description: `Marmara Adası'nın kuzeydoğusundaki Saraylar beldesinde, antik Prokonnesos mermer ocaklarının bulunduğu alan. Roma döneminden kalma yarım kalmış heykeller, lahitler ve mimari parçalar açık havada sergilenmektedir. Adanın mermeri Ayasofya ve Sultanahmet Camii'nde kullanılmıştır.`,
      descriptionEn: `Located in the ancient Proconnesian marble quarries on Marmara Island. Displays unfinished Roman-era sculptures, sarcophagi, and architectural elements. Proconnesian marble was used in Hagia Sophia and the Blue Mosque.`,
      shortDesc: `Antik mermer ocakları ve heykeltıraşlık atölyeleri`, shortDescEn: `Ancient marble quarries and sculpture workshops`,
      latitude: 40.6555, longitude: 27.654, categoryId: ancient.id,
      images: ["https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1024&q=80"],
      visitHours: `Her gün 08:00-18:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Saraylar, Marmara Adası, Balıkesir`, addressEn: `Saraylar, Marmara Island, Balıkesir`,
      publicTransport: `Erdek veya Tekirdağ'dan Marmara Adası'na feribot (1-2 saat). Adada Saraylar'a dolmuş mevcut.`,
      publicTransportEn: `Ferry from Erdek or Tekirdağ to Marmara Island (1-2 hours). Minibus on island to Saraylar.`,
    },
    // ═══ MUSEUMS (12) ═══
    {
      name: `Kuvayi Milliye Müzesi`, nameEn: `National Forces Museum`,
      description: `1840 yılında inşa edilen tarihi konakta yer alır. 15 Mayıs 1919'da İzmir'in işgalinin ertesi günü Kuva-yi Milliye burada kurulmuştur. Zemin katta 41 vatanseverin belgeleri, üst katta arkeolojik ve etnografik eserler sergilenir. 4.979 kayıtlı eser mevcuttur.`,
      descriptionEn: `Housed in a historic mansion built in 1840. The Kuva-yi Milliye was founded here on May 16, 1919. Ground floor displays documents of 41 patriots, upper floor has archaeological and ethnographic artifacts. 4,979 registered items.`,
      shortDesc: `Kurtuluş Savaşı ve Kuvayi Milliye belgeleri`, shortDescEn: `War of Independence and National Forces documents`,
      latitude: 39.6458, longitude: 27.8794, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076082562-e7e3e1e0c1f4?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Anafartalar Cad. No:58, Karesi, Balıkesir`, addressEn: `Anafartalar St. No:58, Karesi, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Çarşı durağında inin. Otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Çarşı stop. 10 min walk from bus station.`,
      isFeatured: true,
    },
    {
      name: `Edremit Zeytinyağı Müzesi`, nameEn: `Edremit Olive Oil Museum`,
      description: `Türkiye'nin ilk ve tek zeytinyağı müzesi. Geleneksel taş baskı yağhanelerden modern üretim tekniklerine kadar zeytinyağı üretiminin tüm aşamaları sergilenir. Edremit zeytinyağının AB Coğrafi İşaret tescili hikayesi de müzenin öne çıkan bölümlerindendir.`,
      descriptionEn: `Turkey's first and only olive oil museum. Exhibits all stages of olive oil production from traditional stone-press mills to modern techniques. Features the story of Edremit olive oil's EU PGI certification.`,
      shortDesc: `Türkiye'nin ilk zeytinyağı müzesi`, shortDescEn: `Turkey's first olive oil museum`,
      latitude: 39.5935, longitude: 27.0164, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1024&q=80"],
      visitHours: `Pazartesi-Cumartesi 09:00-17:00`,
      fee: `15 TL`, feeEn: `15 TRY`,
      address: `Edremit, Balıkesir`, addressEn: `Edremit, Balıkesir`,
      publicTransport: `Balıkesir otogarından Edremit otobüsü (1.5 saat). Edremit merkezden yürüyerek 10 dk.`,
      publicTransportEn: `Bus from Balıkesir to Edremit (1.5 hours). 10 min walk from Edremit center.`,
    },
    {
      name: `Tahtakuşlar Etnografya Müzesi`, nameEn: `Tahtakuşlar Ethnography Museum`,
      description: `Kazdağları eteklerinde, 1991'de emekli öğretmen Alibey Kudar tarafından kurulan özel müze. Tahtacı Türkmenlerinin yaşam kültürünü, geleneksel kıyafetlerini ve kilimlerini sergiler. 197 cm uzunluğunda dev deniz kaplumbağası kabuğu da koleksiyondadır.`,
      descriptionEn: `Private museum at the foothills of Mount Ida, founded in 1991 by retired teacher Alibey Kudar. Dedicated to preserving the Tahtacı Turkmen lifestyle. Collection includes a remarkable 197 cm giant sea turtle shell.`,
      shortDesc: `Yörük kültürü ve göçebe yaşam müzesi`, shortDescEn: `Yörük culture and nomadic life museum`,
      latitude: 39.5911, longitude: 26.8583, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076215667-875c2d76b544?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Tahtakuşlar Köyü, Edremit, Balıkesir`, addressEn: `Tahtakuşlar Village, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Tahtakuşlar köyüne dolmuş mevcut. Kaz Dağları yönüne giden minibüslerle ulaşılır.`,
      publicTransportEn: `Minibus from Edremit to Tahtakuşlar village via Mount Ida minibuses.`,
    },
    {
      name: `Bandırma Arkeoloji Müzesi`, nameEn: `Bandırma Archaeology Museum`,
      description: `2003 yılında açılmış, Güney Marmara'nın en önemli arkeoloji müzelerinden biri. Kyzikos, Daskyleion ve çevre yerleşimlerden çıkarılan Roma, Bizans ve Osmanlı dönemlerine ait lahitler, heykeller, sikkeler sergilenmektedir.`,
      descriptionEn: `Opened in 2003, one of the most significant archaeological museums in the Southern Marmara region. Houses sarcophagi, sculptures, coins from Kyzikos, Daskyleion and surrounding settlements.`,
      shortDesc: `Pers ve antik dönem arkeolojik eserleri`, shortDescEn: `Persian and ancient period archaeological artifacts`,
      latitude: 40.3472, longitude: 27.9533, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Paşakent Mah., Şehit Cemil Kaya Cad. No:17, Bandırma`, addressEn: `Paşakent District, Şehit Cemil Kaya St. No:17, Bandırma`,
      publicTransport: `Balıkesir otogarından Bandırma otobüsü (1.5 saat). İstanbul'dan İDO feribotu ile de ulaşılır. Merkezden yürüyerek 10 dk.`,
      publicTransportEn: `Bus from Balıkesir to Bandırma (1.5 hours). Also IDO ferry from Istanbul. 10 min walk from center.`,
    },
    {
      name: `Gönen Mozaik Müzesi`, nameEn: `Gönen Mosaic Museum`,
      description: `Roma dönemi villalarından çıkarılan mozaik sanatının en seçkin örneklerini barındırır. Mitolojik sahneler, geometrik desenler ve doğa motifleriyle bezeli mozaikler sergilenir.`,
      descriptionEn: `Houses the finest examples of Roman-period mosaic art excavated from villas in the region. Mosaics adorned with mythological scenes, geometric patterns, and nature motifs.`,
      shortDesc: `Roma dönemi mozaik sanatı koleksiyonu`, shortDescEn: `Roman-period mosaic art collection`,
      latitude: 40.1058, longitude: 27.6533, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Gönen, Balıkesir`, addressEn: `Gönen, Balıkesir`,
      publicTransport: `Balıkesir otogarından Gönen otobüsü (1 saat). Gönen merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Bus from Balıkesir to Gönen (1 hour). 5 min walk from Gönen center.`,
    },
    {
      name: `Rahmi M. Koç Müzesi (Cunda)`, nameEn: `Rahmi M. Koç Museum (Cunda)`,
      description: `Cunda Adası'nda tarihi bir zeytinyağı fabrikasında konumlanan özel endüstri müzesi. Antika otomobiller, denizcilik araçları, telgraf makineleri ve erken dönem sanayi ekipmanları sergilenir.`,
      descriptionEn: `Private industrial museum in a historic olive oil factory on Cunda Island. Collection includes antique automobiles, maritime vessels, telegraph machines, and early industrial equipment.`,
      shortDesc: `Endüstriyel miras ve ulaşım tarihi müzesi`, shortDescEn: `Industrial heritage and transportation history museum`,
      latitude: 39.3196, longitude: 26.6948, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1024&q=80"],
      visitHours: `Salı-Pazar 10:00-18:00`,
      fee: `80 TL`, feeEn: `80 TRY`,
      address: `Namık Kemal Mah., 15 Eylül Cd. No:33, Cunda, Ayvalık`, addressEn: `Namık Kemal District, 15 Eylül St. No:33, Cunda, Ayvalık`,
      publicTransport: `Ayvalık merkezden Cunda'ya dolmuş sık sefer yapar (10 dk). Köprü üzerinden yürüyerek de geçilebilir.`,
      publicTransportEn: `Frequent minibuses from Ayvalık center to Cunda (10 min). Also walkable across the bridge.`,
    },
    {
      name: `Bigadiç Müze ve Kültür Evi`, nameEn: `Bigadiç Museum and Culture House`,
      description: `İlçe ölçeğindeki yerel kimliğin halka sunulduğu entegre kültür alanı. Arkeolojik buluntular, etnografik eserler ve yerel el sanatları sergilenir.`,
      descriptionEn: `Integrated cultural space presenting local identity. Displays archaeological finds, ethnographic artifacts, and local handicrafts.`,
      shortDesc: `Yerel kimlik ve kale tarihi`, shortDescEn: `Local identity and castle history`,
      latitude: 39.3926, longitude: 28.1331, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1024&q=80"],
      visitHours: `Salı-Cumartesi 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Bigadiç, Balıkesir`, addressEn: `Bigadiç, Balıkesir`,
      publicTransport: `Balıkesir otogarından Bigadiç otobüsleri günde 6-8 sefer (1 saat). Merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Buses from Balıkesir to Bigadiç 6-8 times daily (1 hour). 5 min walk from center.`,
    },
    {
      name: `Ayşe Sıdıka Erke Etnografya Müzesi`, nameEn: `Ayşe Sıdıka Erke Ethnography Museum`,
      description: `Edremit Belediyesi tarafından kurulmuş özel müze. Kuvâ-yı Milliye odası, geleneksel Türk evi düzeni, el yapımı eserler ve eski silahlar sergilenir. 18.-19. yüzyıl Edremit ev yaşamını yansıtır.`,
      descriptionEn: `Special museum established by Edremit Municipality. Displays a Kuva-yi Milliye room, traditional Turkish house layout, handmade artifacts and antique weapons. Reflects 18th-19th century Edremit domestic life.`,
      shortDesc: `Edremit'in etnografik mirası`, shortDescEn: `Edremit's ethnographic heritage`,
      latitude: 39.59167, longitude: 27.02, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076215667-875c2d76b544?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Soğanyemez Mah., Yılmaz Akpınar Bulvarı No:12A, Edremit`, addressEn: `Soğanyemez District, Yılmaz Akpınar Blvd No:12A, Edremit`,
      publicTransport: `Balıkesir otogarından Edremit otobüsü (1.5 saat). Edremit merkezden yürüyerek 10 dk.`,
      publicTransportEn: `Bus from Balıkesir to Edremit (1.5 hours). 10 min walk from Edremit center.`,
    },
    {
      name: `Devrim Erbil Çağdaş Sanatlar Müzesi`, nameEn: `Devrim Erbil Contemporary Arts Museum`,
      description: `Balıkesirli dünyaca ünlü ressam Devrim Erbil'in eserlerinin sergilendiği çağdaş sanat müzesi. Türk çağdaş sanatının öncü isimlerinden Erbil'in İstanbul manzaraları ve soyut çalışmaları yer alır.`,
      descriptionEn: `Contemporary art museum showcasing works of world-renowned Balıkesir-born painter Devrim Erbil. Features Istanbul landscapes and abstract works by one of the pioneers of Turkish contemporary art.`,
      shortDesc: `Dünyaca ünlü Balıkesirli ressamın müzesi`, shortDescEn: `Museum of world-renowned Balıkesir-born painter`,
      latitude: 39.6486, longitude: 27.8867, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1024&q=80"],
      visitHours: `Salı-Pazar 10:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Karesi Merkez, Balıkesir`, addressEn: `Karesi Center, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Çarşı durağında inin. Otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Çarşı stop. 10 min walk from bus station.`,
    },
    {
      name: `Kazdağı Tabiat Müzesi`, nameEn: `Mount Ida Nature Museum`,
      description: `Kazdağları Milli Parkı içinde yer alan doğa müzesi. Bölgenin endemik bitki ve hayvan türleri, jeolojik yapısı ve ekolojik önemi hakkında interaktif sergiler sunar.`,
      descriptionEn: `Nature museum within Mount Ida National Park. Offers interactive exhibits about the region's endemic flora and fauna, geological structure, and ecological significance.`,
      shortDesc: `Kazdağları'nın doğal mirası`, shortDescEn: `Natural heritage of Mount Ida`,
      latitude: 39.585, longitude: 26.87, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076215667-875c2d76b544?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Kazdağları Milli Parkı, Edremit, Balıkesir`, addressEn: `Mount Ida National Park, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Kazdağları Milli Parkı'na dolmuş veya taksi (30 dk).`,
      publicTransportEn: `Minibus or taxi from Edremit to Mount Ida National Park (30 min).`,
    },
    {
      name: `Burhaniye Kuva-yı Milliye Müzesi`, nameEn: `Burhaniye National Forces Museum`,
      description: `Burhaniye'nin Kurtuluş Savaşı'ndaki rolünü belgeleyen müze. Yerel direnişçilerin fotoğrafları, silahları ve kişisel eşyaları sergilenir.`,
      descriptionEn: `Museum documenting Burhaniye's role in the War of Independence. Displays photographs, weapons, and personal belongings of local resistance fighters.`,
      shortDesc: `Burhaniye'nin Kurtuluş Savaşı mirası`, shortDescEn: `Burhaniye's War of Independence heritage`,
      latitude: 39.5, longitude: 26.97, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076082562-e7e3e1e0c1f4?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Burhaniye Merkez, Balıkesir`, addressEn: `Burhaniye Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Burhaniye otobüsü (1.5 saat). Merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Bus from Balıkesir to Burhaniye (1.5 hours). 5 min walk from center.`,
    },
    {
      name: `Havran Kent Müzesi (Hocazade Konağı)`, nameEn: `Havran City Museum (Hocazade Mansion)`,
      description: `Havran'ın tarihi ve kültürel mirasını sergileyen kent müzesi. Osmanlı dönemi konağında etnografik eserler, yerel el sanatları ve Havran'ın tarihsel belgeleri yer alır.`,
      descriptionEn: `City museum showcasing Havran's historical and cultural heritage. Ottoman-era mansion displays ethnographic artifacts, local handicrafts, and historical documents of Havran.`,
      shortDesc: `Havran'ın tarihi ve kültürel mirası`, shortDescEn: `Havran's historical and cultural heritage`,
      latitude: 39.558, longitude: 27.0975, categoryId: museum.id,
      images: ["https://images.unsplash.com/photo-1590076215667-875c2d76b544?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Havran Merkez, Balıkesir`, addressEn: `Havran Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Havran dolmuşları 30 dk arayla kalkar. Havran merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Minibuses to Havran every 30 min from Balıkesir station. 5 min walk from Havran center.`,
    },
    // ═══ NATURAL AREAS (7) ═══
    {
      name: `Kazdağları Milli Parkı`, nameEn: `Mount Ida National Park`,
      description: `21.300 hektarlık alan üzerinde kurulu, Türkiye'nin en zengin biyoçeşitlilik alanlarından biri. 800'den fazla bitki türü, 100'den fazla kuş türü barındırır. Sarıkız Tepesi (1.774 m) en yüksek noktasıdır. Mitolojide Paris'in Altın Elma'yı verdiği yer olarak bilinir.`,
      descriptionEn: `Spanning 21,300 hectares, one of Turkey's richest biodiversity areas. Home to over 800 plant species and 100 bird species. Sarıkız Peak (1,774 m) is the highest point. Known in mythology as where Paris awarded the Golden Apple.`,
      shortDesc: `21.300 ha biyoçeşitlilik cenneti, mitolojik dağ`, shortDescEn: `21,300 ha biodiversity paradise, mythological mountain`,
      latitude: 39.7, longitude: 26.833, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1024&q=80"],
      visitHours: `Her gün 08:00-20:00 (yaz), 08:00-17:00 (kış)`,
      fee: `Araç girişi 50 TL`, feeEn: `Vehicle entry 50 TRY`,
      address: `Kazdağları Milli Parkı, Edremit, Balıkesir`, addressEn: `Mount Ida National Park, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Kazdağları yönüne dolmuş veya taksi (30 dk). Özel araç tavsiye edilir.`,
      publicTransportEn: `Minibus or taxi from Edremit towards Mount Ida (30 min). Private vehicle recommended.`,
      isFeatured: true,
    },
    {
      name: `Manyas Kuş Cenneti (Kuşcenneti Milli Parkı)`, nameEn: `Manyas Bird Paradise National Park`,
      description: `1959'da Türkiye'nin ilk milli parkı ilan edilen alan. 266 kuş türüne ev sahipliği yapar. Avrupa'nın en önemli kuş göç yollarından biri üzerinde yer alır. UNESCO Dünya Mirası Geçici Listesi'ndedir.`,
      descriptionEn: `Declared Turkey's first national park in 1959. Home to 266 bird species on one of Europe's most important bird migration routes. On UNESCO World Heritage Tentative List.`,
      shortDesc: `Türkiye'nin ilk milli parkı, 266 kuş türü`, shortDescEn: `Turkey's first national park, 266 bird species`,
      latitude: 40.25, longitude: 28.035, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1024&q=80"],
      visitHours: `Her gün 08:00-17:00`,
      fee: `30 TL`, feeEn: `30 TRY`,
      address: `Sığırcı Köyü, Bandırma, Balıkesir`, addressEn: `Sığırcı Village, Bandırma, Balıkesir`,
      publicTransport: `Bandırma'dan Sığırcı köyüne dolmuş (30 dk). Balıkesir'den Bandırma otobüsü (1.5 saat).`,
      publicTransportEn: `Minibus from Bandırma to Sığırcı village (30 min). Bus from Balıkesir to Bandırma (1.5 hours).`,
      isFeatured: true,
    },
    {
      name: `Ayvalık Adaları Tabiat Parkı`, nameEn: `Ayvalık Islands Nature Park`,
      description: `22 ada ve kayalıktan oluşan deniz tabiat parkı. Akdeniz foku, kırmızı mercan ve endemik bitki türlerine ev sahipliği yapar. Dalış, tekne turu ve doğa yürüyüşü için ideal.`,
      descriptionEn: `Marine nature park consisting of 22 islands and islets. Home to Mediterranean monk seals, red coral, and endemic plant species. Ideal for diving, boat tours, and nature walks.`,
      shortDesc: `22 adalık deniz tabiat parkı`, shortDescEn: `Marine nature park with 22 islands`,
      latitude: 39.3475, longitude: 26.6217, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her gün (tekne turları 09:00-18:00)`,
      fee: `Tekne turu 200-400 TL`, feeEn: `Boat tour 200-400 TRY`,
      address: `Ayvalık, Balıkesir`, addressEn: `Ayvalık, Balıkesir`,
      publicTransport: `Ayvalık merkezden tekne turları kalkar. Balıkesir'den Ayvalık otobüsü (3 saat).`,
      publicTransportEn: `Boat tours depart from Ayvalık center. Bus from Balıkesir to Ayvalık (3 hours).`,
    },
    {
      name: `Şeytan Sofrası`, nameEn: `Devil's Table`,
      description: `Ayvalık'ın güneyinde, deniz seviyesinden 354 metre yükseklikte doğal kaya oluşumu. Gün batımı manzarası ile ünlü. Kayada dev bir ayak izi şeklinde çukur bulunur, efsaneye göre şeytanın ayak izidir.`,
      descriptionEn: `Natural rock formation at 354 meters above sea level south of Ayvalık. Famous for sunset views. Features a giant footprint-shaped hollow in the rock, legendarily the devil's footprint.`,
      shortDesc: `354 m'de gün batımı panoraması`, shortDescEn: `Sunset panorama at 354 m elevation`,
      latitude: 39.28917, longitude: 26.64322, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1024&q=80"],
      visitHours: `Her gün, gün batımı saatleri önerilir`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Küçükköy, Ayvalık, Balıkesir`, addressEn: `Küçükköy, Ayvalık, Balıkesir`,
      publicTransport: `Ayvalık merkezden Şeytan Sofrası'na dolmuş veya taksi (15 dk).`,
      publicTransportEn: `Minibus or taxi from Ayvalık center to Devil's Table (15 min).`,
      isFeatured: true,
    },
    {
      name: `Sütüven Şelalesi`, nameEn: `Sütüven Waterfall`,
      description: `Kazdağları Milli Parkı içinde, 15 metre yükseklikten dökülen şelale. Çevresinde yürüyüş parkurları ve piknik alanları bulunur. Yaz aylarında serinlemek için ideal.`,
      descriptionEn: `15-meter waterfall within Mount Ida National Park. Surrounded by hiking trails and picnic areas. Ideal for cooling off in summer months.`,
      shortDesc: `Kazdağları'nın 15 metrelik şelalesi`, shortDescEn: `15-meter waterfall of Mount Ida`,
      latitude: 39.715, longitude: 26.83, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1432405972618-c6b0cfba8b01?w=1024&q=80"],
      visitHours: `Her gün 08:00-19:00 (yaz)`,
      fee: `20 TL`, feeEn: `20 TRY`,
      address: `Kazdağları Milli Parkı, Edremit, Balıkesir`, addressEn: `Mount Ida National Park, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Sütüven yönüne dolmuş veya taksi (25 dk).`,
      publicTransportEn: `Minibus or taxi from Edremit towards Sütüven (25 min).`,
    },
    {
      name: `Şahinderesi Kanyonu`, nameEn: `Şahinderesi Canyon`,
      description: `Kazdağları'nın en etkileyici kanyonlarından biri. 2 km uzunluğunda, 120 metre derinliğinde. Yürüyüş parkurları ve doğa fotoğrafçılığı için popüler.`,
      descriptionEn: `One of the most impressive canyons of Mount Ida. 2 km long, 120 meters deep. Popular for hiking trails and nature photography.`,
      shortDesc: `2 km uzunluğunda, 120 m derinliğinde kanyon`, shortDescEn: `2 km long, 120 m deep canyon`,
      latitude: 39.6627, longitude: 26.8125, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1024&q=80"],
      visitHours: `Her gün gündüz saatleri`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Şahinderesi, Edremit, Balıkesir`, addressEn: `Şahinderesi, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Şahinderesi yönüne taksi (20 dk). Özel araç tavsiye edilir.`,
      publicTransportEn: `Taxi from Edremit towards Şahinderesi (20 min). Private vehicle recommended.`,
    },
    {
      name: `Kapıdağ Yarımadası`, nameEn: `Kapıdağ Peninsula`,
      description: `Marmara Denizi'ne uzanan yarımada. Antik Kyzikos kalıntıları, bakir koylar, zeytinlikler ve balıkçı köyleri ile doğa ve tarih iç içe. Erdek ve Ocaklar plajları ile ünlü.`,
      descriptionEn: `Peninsula extending into the Sea of Marmara. Ancient Kyzikos ruins, pristine coves, olive groves, and fishing villages blend nature and history. Famous for Erdek and Ocaklar beaches.`,
      shortDesc: `Tarih ve doğanın buluştuğu yarımada`, shortDescEn: `Peninsula where history meets nature`,
      latitude: 40.4595, longitude: 27.8517, categoryId: nature.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Kapıdağ Yarımadası, Erdek, Balıkesir`, addressEn: `Kapıdağ Peninsula, Erdek, Balıkesir`,
      publicTransport: `Bandırma'dan Erdek dolmuşları sık sefer yapar (45 dk).`,
      publicTransportEn: `Frequent minibuses from Bandırma to Erdek (45 min).`,
    },
    // ═══ BEACHES & ISLANDS (5) ═══
    {
      name: `Akçay Plajı`, nameEn: `Akçay Beach`,
      description: `Edremit Körfezi'nin en popüler plajlarından biri. Mavi Bayraklı plaj, ince kum yapısı ve sığ denizi ile aileler için ideal. Sahil boyunca kafeler, restoranlar ve su sporları imkanları mevcut.`,
      descriptionEn: `One of the most popular beaches on the Gulf of Edremit. Blue Flag beach with fine sand and shallow waters, ideal for families. Cafes, restaurants, and water sports along the shore.`,
      shortDesc: `Mavi Bayraklı aile plajı`, shortDescEn: `Blue Flag family beach`,
      latitude: 39.5858, longitude: 26.9239, categoryId: beach.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her gün (yaz sezonu Haziran-Eylül)`,
      fee: `Ücretsiz (şezlong ücretli)`, feeEn: `Free (sunbed paid)`,
      address: `Akçay, Edremit, Balıkesir`, addressEn: `Akçay, Edremit, Balıkesir`,
      publicTransport: `Edremit'ten Akçay'a dolmuş sık sefer yapar (15 dk).`,
      publicTransportEn: `Frequent minibuses from Edremit to Akçay (15 min).`,
    },
    {
      name: `Sarımsaklı Plajı`, nameEn: `Sarımsaklı Beach`,
      description: `Ayvalık'ın en ünlü plajı, 7 km uzunluğunda altın kumlu sahil. Mavi Bayraklı plaj, su sporları, sahil barları ve oteller ile yaz turizminin merkezi.`,
      descriptionEn: `Ayvalık's most famous beach, 7 km of golden sand. Blue Flag beach with water sports, beach bars, and hotels, the center of summer tourism.`,
      shortDesc: `7 km altın kumlu Mavi Bayrak plajı`, shortDescEn: `7 km golden sand Blue Flag beach`,
      latitude: 39.2767, longitude: 26.6382, categoryId: beach.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her gün (yaz sezonu Haziran-Eylül)`,
      fee: `Ücretsiz (şezlong ücretli)`, feeEn: `Free (sunbed paid)`,
      address: `Sarımsaklı, Ayvalık, Balıkesir`, addressEn: `Sarımsaklı, Ayvalık, Balıkesir`,
      publicTransport: `Ayvalık merkezden Sarımsaklı'ya dolmuş sık sefer yapar (10 dk).`,
      publicTransportEn: `Frequent minibuses from Ayvalık center to Sarımsaklı (10 min).`,
      isFeatured: true,
    },
    {
      name: `Avşa Adası`, nameEn: `Avşa Island`,
      description: `Marmara Denizi'ndeki tatil adası. Temiz plajları, üzüm bağları ve şarap üretimi ile ünlü. Yaz aylarında İstanbul'dan feribot ile kolayca ulaşılır.`,
      descriptionEn: `Holiday island in the Sea of Marmara. Famous for clean beaches, vineyards, and wine production. Easily accessible by ferry from Istanbul in summer.`,
      shortDesc: `Marmara'nın tatil adası, şarap ve plajlar`, shortDescEn: `Marmara's holiday island, wine and beaches`,
      latitude: 40.5119, longitude: 27.4986, categoryId: beach.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Avşa Adası, Marmara, Balıkesir`, addressEn: `Avşa Island, Marmara, Balıkesir`,
      publicTransport: `Erdek veya İstanbul Yenikapı'dan feribot (2-3 saat).`,
      publicTransportEn: `Ferry from Erdek or Istanbul Yenikapı (2-3 hours).`,
    },
    {
      name: `Erdek Plajları`, nameEn: `Erdek Beaches`,
      description: `Kapıdağ Yarımadası'nın kuzey kıyısında, Marmara Denizi'ne bakan plajlar. Ocaklar, İlhan ve Narlı plajları en popüler olanları. Sakin denizi ve doğal güzellikleri ile tercih edilir.`,
      descriptionEn: `Beaches on the northern coast of Kapıdağ Peninsula facing the Sea of Marmara. Ocaklar, İlhan, and Narlı are the most popular. Preferred for calm waters and natural beauty.`,
      shortDesc: `Kapıdağ'ın Marmara kıyısı plajları`, shortDescEn: `Kapıdağ's Marmara coast beaches`,
      latitude: 40.4, longitude: 27.88, categoryId: beach.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Erdek, Balıkesir`, addressEn: `Erdek, Balıkesir`,
      publicTransport: `Bandırma'dan Erdek dolmuşları sık sefer yapar (45 dk).`,
      publicTransportEn: `Frequent minibuses from Bandırma to Erdek (45 min).`,
    },
    {
      name: `Marmara Adası`, nameEn: `Marmara Island`,
      description: `Marmara Denizi'nin en büyük adası. Antik Prokonnesos mermer ocakları, bakir plajlar ve balıkçı köyleri ile doğa ve tarih iç içe. Saraylar Açık Hava Müzesi adanın en önemli turistik noktasıdır.`,
      descriptionEn: `Largest island in the Sea of Marmara. Ancient Proconnesian marble quarries, pristine beaches, and fishing villages blend nature and history. Saraylar Open-Air Museum is the island's top attraction.`,
      shortDesc: `Marmara'nın en büyük adası, antik mermer ocakları`, shortDescEn: `Marmara's largest island, ancient marble quarries`,
      latitude: 40.6225, longitude: 27.63, categoryId: beach.id,
      images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Marmara Adası, Balıkesir`, addressEn: `Marmara Island, Balıkesir`,
      publicTransport: `Erdek veya Tekirdağ'dan feribot (1-2 saat).`,
      publicTransportEn: `Ferry from Erdek or Tekirdağ (1-2 hours).`,
    },
    // ═══ CULTURAL VENUES (2) ═══
    {
      name: `Ayvalık Tarihi Sokaklar`, nameEn: `Ayvalık Historic Streets`,
      description: `Rum mimarisinin en iyi korunduğu sokaklar. Taş evler, dar sokaklar, zeytinyağı fabrikaları ve kilise kalıntıları ile Osmanlı-Rum kültürel mirasının canlı müzesi. UNESCO Dünya Mirası Geçici Listesi'ndedir.`,
      descriptionEn: `Best-preserved streets of Greek architecture. Stone houses, narrow streets, olive oil factories, and church ruins form a living museum of Ottoman-Greek cultural heritage. On UNESCO World Heritage Tentative List.`,
      shortDesc: `UNESCO adayı Rum mimarisi sokakları`, shortDescEn: `UNESCO-nominated Greek architecture streets`,
      latitude: 39.3193, longitude: 26.6934, categoryId: cultural.id,
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Ayvalık Merkez, Balıkesir`, addressEn: `Ayvalık Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Ayvalık otobüsü (3 saat). İzmir'den de otobüs mevcut (2.5 saat).`,
      publicTransportEn: `Bus from Balıkesir to Ayvalık (3 hours). Also buses from İzmir (2.5 hours).`,
      isFeatured: true,
    },
    {
      name: `Cunda Adası (Alibey Adası)`, nameEn: `Cunda Island (Alibey Island)`,
      description: `Ayvalık'a köprüyle bağlı ada. Rum mimarisi, zeytinlikler, balık restoranları ve sanat galerileri ile Ege'nin en romantik destinasyonlarından biri. Taksiyarhis ve Panayia kiliseleri adanın önemli yapılarıdır.`,
      descriptionEn: `Island connected to Ayvalık by bridge. Greek architecture, olive groves, fish restaurants, and art galleries make it one of the Aegean's most romantic destinations. Taksiyarhis and Panayia churches are notable landmarks.`,
      shortDesc: `Ege'nin romantik adası, Rum mimarisi`, shortDescEn: `Aegean's romantic island, Greek architecture`,
      latitude: 39.3417, longitude: 26.6383, categoryId: cultural.id,
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1024&q=80"],
      visitHours: `Her zaman açık`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Cunda (Alibey) Adası, Ayvalık, Balıkesir`, addressEn: `Cunda (Alibey) Island, Ayvalık, Balıkesir`,
      publicTransport: `Ayvalık merkezden Cunda'ya dolmuş sık sefer yapar (10 dk). Köprü üzerinden yürüyerek de geçilebilir.`,
      publicTransportEn: `Frequent minibuses from Ayvalık center to Cunda (10 min). Also walkable across the bridge.`,
      isFeatured: true,
    },
    // ═══ GASTRONOMY (4) ═══
    {
      name: `Ayvalık Tost Sokağı`, nameEn: `Ayvalık Toast Street`,
      description: `Ayvalık'ın meşhur tostunun doğduğu ve en otantik halinin sunulduğu sokak. Kaşar peyniri, sucuk, domates ve biberle hazırlanan Ayvalık tostu, Türkiye'nin en ünlü sokak lezzetlerinden biridir.`,
      descriptionEn: `The street where Ayvalık's famous toast was born and served in its most authentic form. Made with kaşar cheese, sucuk, tomato, and pepper, Ayvalık toast is one of Turkey's most famous street foods.`,
      shortDesc: `Türkiye'nin en ünlü sokak lezzeti`, shortDescEn: `Turkey's most famous street food`,
      latitude: 39.3189, longitude: 26.6939, categoryId: gastronomy.id,
      images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1024&q=80"],
      visitHours: `Her gün 08:00-23:00`,
      fee: `Tost 50-80 TL`, feeEn: `Toast 50-80 TRY`,
      address: `Ayvalık Merkez, Balıkesir`, addressEn: `Ayvalık Center, Balıkesir`,
      publicTransport: `Ayvalık merkez otogarından yürüyerek 5 dk.`,
      publicTransportEn: `5 min walk from Ayvalık central bus station.`,
      isFeatured: true,
    },
    {
      name: `Edremit Zeytinyağlı Mutfak`, nameEn: `Edremit Olive Oil Cuisine`,
      description: `Edremit Körfezi'nin zeytinyağı kültürünü yansıtan gastronomi deneyimi. Zeytinyağlı yemekler, zeytin çeşitleri ve yerel lezzetler. Edremit zeytinyağı AB Coğrafi İşaret tescillidir.`,
      descriptionEn: `Gastronomy experience reflecting the olive oil culture of the Gulf of Edremit. Olive oil dishes, olive varieties, and local flavors. Edremit olive oil has EU PGI certification.`,
      shortDesc: `AB tescilli zeytinyağı mutfağı`, shortDescEn: `EU-certified olive oil cuisine`,
      latitude: 39.5936, longitude: 27.0244, categoryId: gastronomy.id,
      images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1024&q=80"],
      visitHours: `Restoranlar 11:00-22:00`,
      fee: `Kişi başı 150-300 TL`, feeEn: `Per person 150-300 TRY`,
      address: `Edremit Merkez, Balıkesir`, addressEn: `Edremit Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Edremit otobüsü (1.5 saat).`,
      publicTransportEn: `Bus from Balıkesir to Edremit (1.5 hours).`,
    },
    {
      name: `Gönen Kaymağı`, nameEn: `Gönen Clotted Cream`,
      description: `Gönen'in meşhur kaymağı, manda sütünden geleneksel yöntemlerle üretilir. Kahvaltı sofralarının vazgeçilmezi olan Gönen kaymağı, bal ve tereyağı ile servis edilir.`,
      descriptionEn: `Gönen's famous clotted cream, traditionally produced from water buffalo milk. An essential part of Turkish breakfast, served with honey and butter.`,
      shortDesc: `Manda sütünden geleneksel kaymak`, shortDescEn: `Traditional clotted cream from buffalo milk`,
      latitude: 40.1064, longitude: 27.6536, categoryId: gastronomy.id,
      images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1024&q=80"],
      visitHours: `Kahvaltı mekanları 07:00-12:00`,
      fee: `Porsiyon 40-60 TL`, feeEn: `Portion 40-60 TRY`,
      address: `Gönen Merkez, Balıkesir`, addressEn: `Gönen Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Gönen otobüsü (1 saat).`,
      publicTransportEn: `Bus from Balıkesir to Gönen (1 hour).`,
    },
    {
      name: `Bandırma Balık Hali`, nameEn: `Bandırma Fish Market`,
      description: `Marmara Denizi'nin en taze deniz ürünlerinin satıldığı ve pişirildiği balık hali. Balık restoranları, meyhane kültürü ve deniz mahsulleri ile Bandırma'nın gastronomi merkezi.`,
      descriptionEn: `Fish market where the freshest seafood from the Sea of Marmara is sold and cooked. Fish restaurants, meyhane culture, and seafood make it Bandırma's gastronomy center.`,
      shortDesc: `Marmara'nın en taze deniz ürünleri`, shortDescEn: `Freshest seafood from the Sea of Marmara`,
      latitude: 40.3544, longitude: 27.9722, categoryId: gastronomy.id,
      images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1024&q=80"],
      visitHours: `Her gün 08:00-22:00`,
      fee: `Kişi başı 200-400 TL`, feeEn: `Per person 200-400 TRY`,
      address: `Bandırma Sahil, Balıkesir`, addressEn: `Bandırma Waterfront, Balıkesir`,
      publicTransport: `Balıkesir otogarından Bandırma otobüsü (1.5 saat). İstanbul'dan İDO feribotu ile de ulaşılır.`,
      publicTransportEn: `Bus from Balıkesir to Bandırma (1.5 hours). Also IDO ferry from Istanbul.`,
    },
    // ═══ THERMAL & GEOPARK (3) ═══
    {
      name: `Gönen Kaplıcaları`, nameEn: `Gönen Hot Springs`,
      description: `2000 yıllık geçmişe sahip, Roma döneminden beri kullanılan termal kaynaklar. 82°C sıcaklığındaki sodyum klorürlü, sülfatlı termal sular romatizma, cilt hastalıkları ve solunum yolu rahatsızlıklarına iyi gelir. Modern termal tesisler ve oteller mevcuttur.`,
      descriptionEn: `Thermal springs with 2,000 years of history, used since Roman times. Sodium chloride and sulfate thermal waters at 82°C are beneficial for rheumatism, skin diseases, and respiratory ailments. Modern thermal facilities and hotels available.`,
      shortDesc: `2000 yıllık Roma dönemi termal kaynakları`, shortDescEn: `2,000-year-old Roman-era thermal springs`,
      latitude: 40.1131, longitude: 27.6492, categoryId: thermal.id,
      images: ["https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=1024&q=80"],
      visitHours: `Her gün 07:00-22:00`,
      fee: `Giriş 80-150 TL`, feeEn: `Entry 80-150 TRY`,
      address: `Gönen, Balıkesir`, addressEn: `Gönen, Balıkesir`,
      publicTransport: `Balıkesir otogarından Gönen otobüsü (1 saat). Gönen merkezden yürüyerek 10 dk.`,
      publicTransportEn: `Bus from Balıkesir to Gönen (1 hour). 10 min walk from Gönen center.`,
      isFeatured: true,
    },
    {
      name: `Sındırgı Hisaralan Kaplıcaları`, nameEn: `Sındırgı Hisaralan Hot Springs`,
      description: `Sındırgı'nın UNESCO Küresel Jeopark adaylık sürecindeki en önemli termal alanlarından biri. 60-95°C sıcaklığındaki termal sular, doğal orman içinde konumlanmış tesislerde sunulur.`,
      descriptionEn: `One of the most important thermal areas in Sındırgı's UNESCO Global Geopark candidacy. Thermal waters at 60-95°C are offered in facilities set within natural forest.`,
      shortDesc: `UNESCO Jeopark adayı termal alan`, shortDescEn: `UNESCO Geopark candidate thermal area`,
      latitude: 39.237, longitude: 28.175, categoryId: thermal.id,
      images: ["https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=1024&q=80"],
      visitHours: `Her gün 08:00-21:00`,
      fee: `Giriş 60-120 TL`, feeEn: `Entry 60-120 TRY`,
      address: `Hisaralan, Sındırgı, Balıkesir`, addressEn: `Hisaralan, Sındırgı, Balıkesir`,
      publicTransport: `Balıkesir otogarından Sındırgı otobüsü (1.5 saat), ardından Hisaralan dolmuşu (20 dk).`,
      publicTransportEn: `Bus from Balıkesir to Sındırgı (1.5 hours), then minibus to Hisaralan (20 min).`,
    },
    {
      name: `Kepsut Jeotermal Tesisleri`, nameEn: `Kepsut Geothermal Facilities`,
      description: `Kepsut ilçesinde bulunan jeotermal kaynaklar. Termal sular sera ısıtması ve termal turizm için kullanılır. Bölgenin gelişen jeotermal enerji potansiyeli ile dikkat çeker.`,
      descriptionEn: `Geothermal sources in Kepsut district. Thermal waters used for greenhouse heating and thermal tourism. Notable for the region's growing geothermal energy potential.`,
      shortDesc: `Jeotermal enerji ve termal turizm`, shortDescEn: `Geothermal energy and thermal tourism`,
      latitude: 39.6889, longitude: 28.1522, categoryId: thermal.id,
      images: ["https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=1024&q=80"],
      visitHours: `Her gün 08:00-20:00`,
      fee: `Giriş 50-100 TL`, feeEn: `Entry 50-100 TRY`,
      address: `Kepsut, Balıkesir`, addressEn: `Kepsut, Balıkesir`,
      publicTransport: `Balıkesir otogarından Kepsut dolmuşları günde 6-8 sefer (45 dk).`,
      publicTransportEn: `Minibuses from Balıkesir to Kepsut 6-8 times daily (45 min).`,
    },
    // ═══ RELIGIOUS SITES (4) ═══
    {
      name: `Taksiyarhis Kilisesi`, nameEn: `Taksiyarhis Church`,
      description: `Ayvalık merkezde 1844 yılında inşa edilen Rum Ortodoks kilisesi. Neoklasik üslupta tasarlanmış, iç mekanında özgün freskler ve ikonalar korunmuştur. Restorasyon sonrası kültür merkezi ve sergi mekanı olarak hizmet vermektedir.`,
      descriptionEn: `Greek Orthodox church built in 1844 in Ayvalık center. Designed in neoclassical style with original frescoes and icons preserved inside. After restoration, serves as a cultural center and exhibition venue.`,
      shortDesc: `1844 Rum Ortodoks kilisesi, kültür merkezi`, shortDescEn: `1844 Greek Orthodox church, cultural center`,
      latitude: 39.31889, longitude: 26.69417, categoryId: religious.id,
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1024&q=80"],
      visitHours: `Salı-Pazar 09:00-17:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Ayvalık Merkez, Balıkesir`, addressEn: `Ayvalık Center, Balıkesir`,
      publicTransport: `Ayvalık merkez otogarından yürüyerek 10 dk.`,
      publicTransportEn: `10 min walk from Ayvalık central bus station.`,
      isFeatured: true,
    },
    {
      name: `Yıldırım Bayezid Camii (Edremit)`, nameEn: `Yıldırım Bayezid Mosque (Edremit)`,
      description: `Edremit'te 1392 yılında Yıldırım Bayezid tarafından yaptırılan cami. Erken Osmanlı mimarisinin Edremit'teki en önemli örneği. Dikdörtgen planlı, tek kubbeli yapı.`,
      descriptionEn: `Mosque built in 1392 by Sultan Bayezid I in Edremit. The most important example of early Ottoman architecture in Edremit. Rectangular plan with single dome.`,
      shortDesc: `1392 Erken Osmanlı camii`, shortDescEn: `1392 Early Ottoman mosque`,
      latitude: 39.5962, longitude: 27.0243, categoryId: religious.id,
      images: ["https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=1024&q=80"],
      visitHours: `Her gün 05:00-22:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Edremit Merkez, Balıkesir`, addressEn: `Edremit Center, Balıkesir`,
      publicTransport: `Balıkesir otogarından Edremit otobüsü (1.5 saat). Edremit merkezden yürüyerek 5 dk.`,
      publicTransportEn: `Bus from Balıkesir to Edremit (1.5 hours). 5 min walk from Edremit center.`,
    },
    {
      name: `Balıkesir Ulu Camii (Zağnos Paşa Camii Yanı)`, nameEn: `Balıkesir Grand Mosque`,
      description: `Balıkesir'in tarihi merkezinde yer alan ulu cami. Osmanlı döneminde inşa edilmiş, şehrin en önemli ibadet mekanlarından biri. Zağnos Paşa Camii ile birlikte dini mimari bütünlük oluşturur.`,
      descriptionEn: `Grand mosque in the historic center of Balıkesir. Built during the Ottoman period, one of the city's most important places of worship. Forms a religious architectural ensemble with Zağnos Paşa Mosque.`,
      shortDesc: `Balıkesir'in tarihi ulu camii`, shortDescEn: `Balıkesir's historic grand mosque`,
      latitude: 39.648, longitude: 27.88, categoryId: religious.id,
      images: ["https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=1024&q=80"],
      visitHours: `Her gün 05:00-22:00`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Karesi Merkez, Balıkesir`, addressEn: `Karesi Center, Balıkesir`,
      publicTransport: `Merkez belediye otobüsleri ile Çarşı durağında inin. Otogardan yürüyerek 10 dk.`,
      publicTransportEn: `Take city buses to Çarşı stop. 10 min walk from bus station.`,
    },
    {
      name: `Panayia Kilisesi (Cunda)`, nameEn: `Panayia Church (Cunda)`,
      description: `Cunda Adası'nda 1873 yılında inşa edilen Rum Ortodoks kilisesi. Adanın en büyük kilisesi olup neoklasik mimarisi ve çan kulesi ile dikkat çeker. Restorasyon çalışmaları devam etmektedir.`,
      descriptionEn: `Greek Orthodox church built in 1873 on Cunda Island. The island's largest church, notable for its neoclassical architecture and bell tower. Restoration work is ongoing.`,
      shortDesc: `1873 Cunda'nın en büyük Rum kilisesi`, shortDescEn: `1873 Cunda's largest Greek church`,
      latitude: 39.33611, longitude: 26.66167, categoryId: religious.id,
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1024&q=80"],
      visitHours: `Dış mekan her zaman, iç mekan restorasyon durumuna göre`,
      fee: `Ücretsiz`, feeEn: `Free`,
      address: `Cunda Adası, Ayvalık, Balıkesir`, addressEn: `Cunda Island, Ayvalık, Balıkesir`,
      publicTransport: `Ayvalık merkezden Cunda'ya dolmuş sık sefer yapar (10 dk). Köprü üzerinden yürüyerek de geçilebilir.`,
      publicTransportEn: `Frequent minibuses from Ayvalık center to Cunda (10 min). Also walkable across the bridge.`,
    },
  ];

  for (const loc of locations) {
    await prisma.location.create({ data: loc });
  }

  // ── Admin ──
  const hashedPassword = await bcrypt.hash("admin123", 12);
  await prisma.admin.create({
    data: {
      username: "admin",
      email: "admin@balikesir.bel.tr",
      password: hashedPassword,
      name: "Sistem Yöneticisi",
      role: "SYSTEM_ADMIN",
    },
  });

  console.log("✅ Seed completed: " + locations.length + " locations, 9 categories, 1 admin");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
